const ROUTE_CHANGED = 'ROUTE_CHANGED'
const CHANGE_ROUTE = 'CHANGE_ROUTE'
const LOAD_USER_DATA = 'LOAD_USER_DATA'
const SHOW_LOADER = 'SHOW_LOADER'
const HIDE_LOADER = 'HIDE_LOADER'
const ERROR_HANDLER = 'ERROR_HANDLER'
const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS'
const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE'
const CLEAR_AUTH = 'CLEAR_AUTH'
export {
  SHOW_LOADER,
  HIDE_LOADER,
  CLEAR_AUTH,
  CHANGE_ROUTE,
  ROUTE_CHANGED,
  ERROR_HANDLER,
  LOAD_USER_DATA,
  FETCH_LOGIN_FAILURE,
  FETCH_LOGIN_SUCCESS
}
